# Generated by Django 4.0.4 on 2022-07-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrega_app', '0005_alter_post_options_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_post',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.CharField(max_length=60),
        ),
    ]
